
on: [push, pull_request]

name: libp2p-bitswap

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - rust: stable
        #- rust: nightly
        platform:
          - target: x86_64-unknown-linux-gnu
            host: ubuntu-latest
            cross: false

          - target: x86_64-apple-darwin
            host: macos-latest
            cross: false

          - target: x86_64-pc-windows-msvc
            host: windows-latest
            cross: false

          - target: armv7-linux-androideabi
            host: ubuntu-latest
            cross: true
          - target: aarch64-linux-android
            host: ubuntu-latest
            cross: true

          - target: aarch64-apple-ios
            host: macos-latest
            cross: true

        # - target: wasm32-unknown-unknown
        #   host: ubuntu-latest
        #   cross: true
    env: