
on: [push, pull_request]

name: libp2p-bitswap

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - rust: stable
        #- rust: nightly
        platform:
          - target: x86_64-unknown-linux-gnu
            host: ubuntu-latest
            cross: false

          - target: x86_64-apple-darwin
            host: macos-latest
            cross: false

          - target: x86_64-pc-windows-msvc
            host: windows-latest
            cross: false

          - target: armv7-linux-androideabi
            host: ubuntu-latest
            cross: true
          - target: aarch64-linux-android
            host: ubuntu-latest
            cross: true

          - target: aarch64-apple-ios
            host: macos-latest
            cross: true

        # - target: wasm32-unknown-unknown
        #   host: ubuntu-latest
        #   cross: true
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      CARGO_INCREMENTAL: 0
      LLVM_CONFIG_PATH: /usr/local/opt/llvm/bin/llvm-config
      NDK_HOME: /usr/local/lib/android/sdk/ndk-bundle

    runs-on: ${{ matrix.platform.host }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Cache cargo folder
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.platform.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies ubuntu
        if: matrix.platform.host == 'ubuntu-latest'
        run: sudo apt-get install llvm-dev
